# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jchat', '0002_auto_20160711_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 11, 14, 16, 1, 586173, tzinfo=utc)),
        ),
    ]
