# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatpop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpop',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_sent_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatpop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sent_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
