# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
